library('arules')
library('arulesViz')
data(Groceries)
itemsets<-apriori(Groceries,parameter=list(minlen=1,support=0.02,target="frequent itemsets"))
inspect(head(sort(itemsets,by="support"),10))
rules<-apriori(Groceries,parameter=list(support=0.02,confidence=0.09,target="rules"))
summary(rules)
print(rules)
print(rules@quality)
confidentRules<-rules[quality(rules)$confidence>0.3]
summary(confidentRules)
print(confidentRules)
inspect(head(sort(rules,by="confidence"),10))
inspect(head(sort(rules,by="lift"),10))
plot(rules@quality)
plot(rules)
plot(confidentRules)