library('ISLR')  
carseats<-Carseats
High <- ifelse(carseats$Sales<=8, "No", "Yes")
carseats <- data.frame(carseats, High)
View(carseats)
require(tree)
tree.carseats <- tree(High~.-Sales, data=carseats)
summary(tree.carseats) 
train <- sample(1:nrow(carseats), 250)
tree.carseats <- tree(High~.-Sales, carseats, subset=train)
plot(tree.carseats)
text(tree.carseats, pretty=0)
tree.pred <- predict(tree.carseats, carseats[-train,], type="class")
with(carseats[-train,], table(tree.pred, High))
cv.carseats <- cv.tree(tree.carseats, FUN = prune.misclass)
cv.carseats
prune.carseats <- prune.misclass(tree.carseats, best = 12)
plot(prune.carseats)
text(prune.carseats, pretty=0) 
tree.pred <- predict(prune.carseats, carseats[-train,], type="class")
with(carseats[-train,], table(tree.pred, High))